### ISSUE TITLE
CDLC Segment depends on openssl, which isn't shipped on 10.11

### ISSUE THREAD

**Issue by strangewiz** [nygard/class-dump#56]
http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html

**Comment by nygard** [comment]
This should be fixed in 2707d03.  I've switched to CommonCrypto for decryption, now that it supports Blowfish.

Thanks!

**Comment by DomT4** [comment]
Not sure if this is quite the same issue, but the latest commit here still links to the OpenSSL libraries:

```
/usr/local/bin/class-dump:
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1252.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1253.0.0)
```

**Comment by apjanke** [comment]
Looks like the Xcode project still has a reference to `libcrypto` even though nothing in it is being used, so it's still being linked. #58 removes it.

<img width="330" alt="screen shot 2015-09-27 at 1 43 39 pm" src="https://cloud.githubusercontent.com/assets/2618447/10124225/efbffe6a-651d-11e5-8be0-f0ac9dc7be92.png">

**Comment by selectersky** [comment]
build failed:
The following build commands failed:
	Libtool build/Release/libMachObjC.a normal x86_64
(1 failure)

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
class-dump failed to build on 10.11 https://github.com/Homebrew/homebrew/issues/42384
