### ISSUE TITLE
Error when generating headers for Dock on El Capitan 

### ISSUE THREAD

**Issue by triplegit** [nygard/class-dump#60]
When trying to generate header files for the Dock app on El Capitan (OS 10.11.1), I am receiving the following error "Error: Cannot find offset for address 0x8100000000000000 in dataOffsetForAddress:".

The same command works great on Yosemite (OS 10.10.5). Any ideas on why this might be happening? Any clues of where I could start investigating would also be appreciated.

Thank you.

**Comment by FredericJacobs** [comment]
AFAIK the Dock was completely rewritten in Swift.

**Comment by nygard** [comment]
I just pushed a change to recognize Swift classes, and this lets it get further when dumping the Dock.  There are still errors with parsing some ivar types, and the Swift class names aren't demangled.

**Comment by triplegit** [comment]
I just tried it and it works like a charm. Thank you very much.

**Comment by Charybdis** [comment]
.@triplegit I'm getting the same error, using 3.5. My guess is that it's because the Dock binary (10.11) is encrypted? If I understand correctly, `deprotect` will fix this problem, but it's failing to decrypt it for me. This was the error:
```
2016-10-07 21:33:38.655 deprotect[71105:3689711] *** Assertion failure in -[CDLCSegment decryptedData], /Users/name/macOS/classdump/class-dump/Source/CDLCSegment.m:259
2016-10-07 21:33:38.656 deprotect[71105:3689711] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: status == kCCSuccess'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff953354f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8b74273c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9533a1ca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8e68c856 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   deprotect                           0x000000010d39f1b1 deprotect + 33201
	5   deprotect                           0x000000010d398582 deprotect + 5506
	6   deprotect                           0x000000010d398b91 deprotect + 7057
	7   libdyld.dylib                       0x00007fff8fff85ad start + 1
	8   ???                                 0x0000000000000003 0x0 + 3
)
```
If anyone is aware of a working way to decrypt the 10.11 Dock binary, I'd love to hear about it.

**Comment by sdsykes** [comment]
I find I can deprotect Dock with deprotect 3.5 fine. 3.3.4 also works but with some warnings. Tested on latest 10.12 Dock, and 10.11.1 which is the latest 10.11 I have around on this machine. I don't see the error you are seeing.

**Comment by 0xced** [comment]
Could it be that @sdsykes is testing on El Capitan and @Charybdis on Sierra?

Apparently, there were some [changes in Sierra for blowfish](http://blog.timac.org/?p=1086).

I haven't actually looked at the code, I just speculated over this: `Invalid parameter not satisfying: status == kCCSuccess`.

**Comment by Charybdis** [comment]
@sdsykes thanks for the reply. I suppose there's a little more to the story, but I'm not sure this is the problem. When I build this using Xcode 8, it complains about not being able to find libcrypto (`ld: library not found for -lcrypto`). After a little googling, I found this and used it to build the necessary dylib: https://gist.github.com/tmiz/1441111
But, perhaps that's where my error is. Do you recall where you got libcrypto from?
I don't plan on making any changes to the class-dump or deprotect source, if you don't mind uploading compiled binaries somewhere that would be awesome too :)

**Comment by Charybdis** [comment]
@0xced the `status == kCCSuccess` check is right after this function call:
```
CCCryptorStatus status = CCCryptorCreate(kCCDecrypt, kCCAlgorithmBlowfish, 0, keyData, sizeof(keyData), NULL, &cryptor);
```
When I look at the definition for `CCCryptorCreate`, I see it's under the 10.12 SDK, and I'm on 10.11. I guess I should either update to 10.12 or download Xcode 7, assuming that fix you linked to is the source of what's causing the error.

**Comment by sdsykes** [comment]
My version I compiled in June 2015, so that was likely on Mavericks. I'll email you a link to it.

**Comment by Charybdis** [comment]
Awesome, what you sent me worked.

If anyone else stumbles upon this thread and has trouble compiling the deprotect binary, I uploaded them here: http://ash.ag/classdump3.5/

**Comment by JusTomm** [comment]
Is there a version that supports Linux?
