### ISSUE TITLE
Building from source as iOS binary only

### ISSUE THREAD

**Issue by fxfactorial** [nygard/class-dump#63]
I'm trying to build from source in Xcode by opening the project in XCode and changing in build settings the SDK to use to iOS instead of OS X on latest versions of OS X and XCode and I get errors like:

```
target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphonesimulator' platform
```

What do I have to do to make this build as a binary intended to run on iOS, say armv7 or arm64.

Also, I'd ideally like the `xcodebuild` invocation that can do this so that I can see what needs to be built with what flags, etc, so I can make a makefile out of this.

I tried this:
```shell
$ xcodebuild -sdk iphoneos -scheme class-dump build
```
But got an error of:
```shell
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Edgar/Library/Developer/Xcode/DerivedData/class-dump-dytpevsctimenkfnziaegkkdeltg/Build/Intermediates/class-dump.build/Debug-iphoneos/MachObjC.build/Objects-normal/armv7/CDLCSegment.o Source/CDLCSegment.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```
Thank you.

**Comment by fxfactorial** [comment]
Okay, if the code needs to be updated for iOS could some guidance be issued at least, im willing to do the work.

**Comment by nygard** [comment]
I can't help you -- I don't have a jailbroken device and have never tried to compile this for ios.

**Comment by fxfactorial** [comment]
Okay thank you.
