### ISSUE TITLE
How can  i get iPhone Bluetooth Address

### ISSUE THREAD

**Issue by luoxubin** [nygard/class-dump#64]
Is there a way to get the iPhone Bluetooth Address？
And how can get the  information （such as  name，address） of the Bluetooth Device connected
to iPhone?
thank you very much.

**Comment by markcoker** [comment]
First... This isn't the place for questions like that. https://www.reddit.com/r/jailbreak maybe?

To answer your question, use **_ifconfig_** like you would on linux or a Mac.

Or use **_HE.NET Network Tools_** App.
