### ISSUE TITLE
libcrypto.dylib gone on sierra

### ISSUE THREAD

**Issue by ioquatix** [nygard/class-dump#70]
Hey, just a heads up, the linker dependency `libcrypto.dylib` is gone and can be safely removed for this platform. It's now (apparently) incorporated into libSystem which is included by default. I've tested building without this and it works fine :)

**Comment by marcelogaio** [comment]
@ioquatix Can you post the changes made? I tried to recompile but got errors :(
Thanks!!

**Comment by ioquatix** [comment]
I just removed lib crypto from the Xcode project.

**Comment by nygard** [comment]
Thanks, this has been fixed.
