### ISSUE TITLE
Error: Cannot find offset for address 0x280000000102fee7 in stringAtAddress:

### ISSUE THREAD

**Issue by ohmza** [nygard/class-dump#81]
2018-02-24 22:20:05.557 class-dump[37068:3215623] Error: Cannot find offset for address 0x280000000102fee7 in stringAtAddress:

Here is a link of the sample executable that could not be dumped -> https://www.sendspace.com/file/o5hzwn

**Comment by abjurato** [comment]
This is duplicate of https://github.com/nygard/class-dump/issues/51. As mentioned there, you should build class-dump from sources since fix did not enter into latest release

**Comment by drummingdemon** [comment]
Built from source, the error message stays the same - any other suggestions?

**Comment by nygard** [comment]
The current version doesn't have this error in any files I've tested.  The link is expired, so I can't test against that file.
