### ISSUE TITLE
Add iOS 12 support

### ISSUE THREAD

**Issue by AndrzejMistetskij** [nygard/class-dump#82]
MacBook-Pro-Andrzej:class-dump amist$ ./class-dump /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit 
2018-06-07 17:48:45.935 class-dump[15689:6032973] Unknown load command: 0x00000032
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
// UUID: 1D5A0E4C-DBE1-3DAF-B027-7D18BB4A3F6A
//
//                           Arch: x86_64
//                Current version: 61000.0.0
//          Compatibility version: 1.0.0
//                 Source version: 3698.8.9.0.0
//

//
// This file does not contain any Objective-C runtime information.
//

**Comment by KAnoshkin** [comment]
@AndrzejMistetskij Try UIKitCore instead as UIKit now looks like a shim.

**Comment by ahyattdev** [comment]
I get the same error with `DirectoryService.framework` on macOS.

```
$ class-dump /System/Library/Frameworks/DirectoryService.framework/DirectoryService 
2018-11-23 22:42:51.756 class-dump[4384:296692] Unknown load command: 0x00000032
```

**Comment by nygard** [comment]
Right, it looks like UIKit just reexports some dylibs, including UIKitCore.  You can use otool -lv on the original file to see the re-exported dylib.

Or you could try:
/Local/nygard/Debug/class-dump -r --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
which spits out some warnings but does produce output.

**Comment by WuKongCoo1** [comment]
I get the same error, below is info

class-dump -H TestReverse
2019-07-24 16:09:16.309 class-dump[89691:6702435] Unknown load command: 0x00000032

TestReverse is from a iOS 12 ipa

**Comment by WuKongCoo1** [comment]
> Right, it looks like UIKit just reexports some dylibs, including UIKitCore. You can use otool -lv on the original file to see the re-exported dylib.
> 
> Or you could try:
> /Local/nygard/Debug/class-dump -r --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
> which spits out some warnings but does produce output.

I get this information 
class-dump -r --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
2019-07-24 16:32:43.606 class-dump[90161:6738990] Unknown load command: 0x00000032
2019-07-24 16:32:43.608 class-dump[90161:6738990] Unknown load command: 0x00000032
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
// UUID: A981CA84-A6B5-3113-9575-E2482946CD68
//
//                           Arch: x86_64
//                Current version: 61000.0.0
//          Compatibility version: 1.0.0
//                 Source version: 3698.39.12.0.0
//

//
// This file does not contain any Objective-C runtime information.
//
#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib
// UUID: E21EFB7E-8C79-33E5-9E54-E4DB00201F40
//
//                           Arch: x86_64
//                Current version: 1252.250.1
//          Compatibility version: 1.0.0
//                 Source version: 1252.58.1.0.0
//

//
// This file does not contain any Objective-C runtime information.

**Comment by WuKongCoo1** [comment]
> > Right, it looks like UIKit just reexports some dylibs, including UIKitCore. You can use otool -lv on the original file to see the re-exported dylib.
> > Or you could try:
> > /Local/nygard/Debug/class-dump -r --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
> > which spits out some warnings but does produce output.
> 
> I get this information
> class-dump -r --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
> 2019-07-24 16:32:43.606 class-dump[90161:6738990] Unknown load command: 0x00000032
> 2019-07-24 16:32:43.608 class-dump[90161:6738990] Unknown load command: 0x00000032
> //
> // Generated by class-dump 3.5 (64 bit).
> //
> // class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
> //
> 
> //
> // SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
> //
> 
> #pragma mark -
> 
> //
> // File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
> // UUID: A981CA84-A6B5-3113-9575-E2482946CD68
> //
> // Arch: x86_64
> // Current version: 61000.0.0
> // Compatibility version: 1.0.0
> // Source version: 3698.39.12.0.0
> //
> 
> //
> // This file does not contain any Objective-C runtime information.
> //
> #pragma mark -
> 
> //
> // File: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib
> // UUID: E21EFB7E-8C79-33E5-9E54-E4DB00201F40
> //
> // Arch: x86_64
> // Current version: 1252.250.1
> // Compatibility version: 1.0.0
> // Source version: 1252.58.1.0.0
> //
> 
> //
> // This file does not contain any Objective-C runtime information.

I solve this by replace class_dump with source project file

**Comment by plumhly** [comment]
you can use UIKitCore.framework

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework

**Comment by efremidze** [comment]
Xcode 12 Beta iOS 14 UIKitCore.framework

/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework
