### ISSUE TITLE
Better swift support please

### ISSUE THREAD

**Issue by ZZinKin** [nygard/class-dump#84]
Swift is not supported because of [issue51](https://github.com/nygard/class-dump/issues/51).I merged the [code here](https://github.com/nygard/class-dump/pull/43/files), it won't crash but it isn't perfect.Pure swift code contains no method and no variable/property, maybe it's time to upgrade a new release.

**Comment by nygard** [comment]
Swift types have a blank encoding, so there's nothing class-dump can do when the information is missing.
