### ISSUE TITLE
Can't parse type std::atomic<NSInteger>

### ISSUE THREAD

**Issue by wujianbotju** [nygard/class-dump#87]
When I tried to generate header files from application using react native, I found parsing error for member std::atomic\<NSInteger\> _pendingCount of class RCTCxxBridge.

Warning: Parsing instance variable type failed, _pendingCount(name), {atomic<long>="__a_"Aq}(type)

**Comment by nygard** [comment]
I don't have a React Native app to test against, but this should be fixed now after my recent changes.  The problem was the "A", from "Aq", which is _Atomic(long long).
