### ISSUE TITLE
Invalid parameter not satisfying: listHeader.entsize == 3 * [self.machOFile ptrSize]

### ISSUE THREAD

**Issue by kazzmir** [nygard/class-dump#98]
Running class-dump on some binaries in the latest ios 14.0 image from xcode 12 beta results in the following error:
```
$ class-dump gputoolsd
2020-06-23 13:38:24.836 class-dump[17849:24720485] *** Assertion failure in -[CDObjectiveC2Processor loadMethodsAtAddress:extendedMethodTypesCursor:], /Users/me/tmp/class-dump/Source/CDObjectiveC2Processor.m:404
2020-06-23 13:38:24.837 class-dump[17849:24720485] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: listHeader.entsize == 3 * [self.machOFile ptrSize]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff42b40cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6d6f3a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff42b5ba16 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff44dede11 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   class-dump                          0x00000001015416a1 -[CDObjectiveC2Processor loadMethodsAtAddress:extendedMethodTypesCursor:] + 1120
	5   class-dump                          0x0000000101540213 -[CDObjectiveC2Processor loadClassAtAddress:] + 766
	6   class-dump                          0x000000010153e998 -[CDObjectiveC2Processor loadClasses] + 243
	7   class-dump                          0x000000010153bccc -[CDObjectiveCProcessor process] + 391
	8   class-dump                          0x000000010151a0b0 -[CDClassDump processObjectiveCData] + 344
	9   class-dump                          0x000000010152b5f7 main + 3459
	10  libdyld.dylib                       0x00007fff6ef213d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```
This occurs for many of the binaries in the ios 14 DeveloperDiskImage.

For reference, the image can be mounted via hdiutil.
```
~/tmp/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.0 $ hdiutil mount DeveloperDiskImage
cd /Volumes/DeveloperDiskImage
```

This issue seems to only affect binaries in the 14.0 image.

**Comment by MLKrisJohnson** [comment]
I suspect this is related to this item in the Xcode 12 release notes:

> When the deployment target is iOS 14 or higher, the linker now converts Objective-C method lists into a new, smaller, read-only relative methods list in __TEXT. These binaries will not work on older versions of iOS or iPadOS. (56880461)

<https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes>

**Comment by malhal** [comment]
Dup of #68 & #72

**Comment by malhal** [comment]
> I suspect this is related to this item in the Xcode 12 release notes:
> 
> > When the deployment target is iOS 14 or higher, the linker now converts Objective-C method lists into a new, smaller, read-only relative methods list in __TEXT. These binaries will not work on older versions of iOS or iPadOS. (56880461)
> 
> https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes

And explained in the video [Advancements in the Objective-C runtime](https://developer.apple.com/videos/play/wwdc2020/10163/)

**Comment by kazzmir** [comment]
Lets move to #68
